"""Adding required tables

Revision ID: ba37d67050cd
Revises: 
Create Date: 2022-02-20 11:19:55.929111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba37d67050cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('cmc_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cmc_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_crypto_assets_id'), 'crypto_assets', ['id'], unique=False)
    op.create_index(op.f('ix_crypto_assets_ticker'), 'crypto_assets', ['ticker'], unique=True)
    op.create_table('assets_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crypto_asset_id', sa.Integer(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crypto_asset_id'], ['crypto_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github')
    )
    op.create_index(op.f('ix_assets_urls_id'), 'assets_urls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_urls_id'), table_name='assets_urls')
    op.drop_table('assets_urls')
    op.drop_index(op.f('ix_crypto_assets_ticker'), table_name='crypto_assets')
    op.drop_index(op.f('ix_crypto_assets_id'), table_name='crypto_assets')
    op.drop_table('crypto_assets')
    # ### end Alembic commands ###
